version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb'
    # volumes:
    #   - 'mongodb_data:/bitnami'

  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/node:latest'
    command: sh -c 'npm install && node app.js'
    environment:
      APOS_MONGODB_URI: 'mongodb://mongodb:27017'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

# volumes:
#   mongodb_data:
#     driver: local
