version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'

  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/node:latest'
    command: sh -c 'npm install && node app.js'
    environment:
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      APOS_MONGODB_URI: 'mongodb://mongodb:27017'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

