version: '2'

services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/node:latest'
    labels:
      kompose.service.type: nodeport
    command: sh -c 'npm install && node app.js'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      APOS_MONGODB_URI: 'mongodb://mongodb:27017'
  mongodb:
    tty: true
    image: 'bitnami/mongodb'
    ports:
      - 27017:27017
